### ISSUE TITLE
/home: Thumbnail of video too alarming

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#1]

**Comment by plexish** [comment]
@melissasamworth do you have takes on what the thumbnail should be?

**Comment by melissasamworth** [comment]
Anything that's not the world ending 😆. The first frame of the video would be good. I was also happy with the one Bryce chose.

**Comment by melissasamworth** [comment]
Update: This one!



![Image](https://github.com/StampyAI/AISafety.com/assets/825910/d4cdec32-2041-46b3-8bc0-e57cfe7f22c8)
