### ISSUE TITLE
/events: too little info, should add most of aisafety.training or split between two pages

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#10]

**Comment by melissasamworth** [comment]
Didn't you say events and training should be separate pages?

I never designed the events page, just imported a few airtable views. If we want to prioritize really designing this, I'd like to learn more about events and such and discuss on call!

**Comment by ricewithabee** [comment]
Update: For now we're going to just add both training programs and events to /events until a separate page is made later for training programs. Bryce will do this.

**Comment by bryceerobertson** [comment]
This is a duplicate
