### ISSUE TITLE
some featured items are repeated in the list below

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#100]
I think it's best to avoid this

For instance on courses, AISF is featured, then repeated a few times underneath

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/c5c1b417-7d99-4674-be72-42fc17485ff4)

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/c70a280b-328d-4182-a9ee-f8668950ae54)

**Comment by melissasamworth** [comment]
@soerenelverlin I remember you mentioning this, but feel free to not prioritize it right now, your call

**Comment by bryceerobertson** [comment]
Agreed, I can do this

**Comment by bryceerobertson** [comment]
Update: remove this using the filter.
