### ISSUE TITLE
/projects, /funders: reflect the correct database columns in Webflow

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#101]
/projects

Status NEW column needs to be hooked up to Whalesync and then reflected on the cards

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/e094a472-70e5-41dc-a8ab-bbf3b0940688)

Same with contact email column

/funders

Actually let's have a conversation about this on the next call because there are some design decisions to be made

**Comment by melissasamworth** [comment]
@bryceerobertson Assigning you but feel free to reassign to Soern

**Comment by bryceerobertson** [comment]
The ones for /projects are done. Do you want me to implement that in the Webflow design or will you do that?

**Comment by melissasamworth** [comment]
> The ones for /projects are done. Do you want me to implement that in the Webflow design or will you do that?
> 
> Btw I've had to publish to .com in order to make Whalesync work.

Sorry yeah that should generally be my job. Looks good, not sure whether that was you or me heh
