### ISSUE TITLE
/home: Watch video CTA could be larger

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#11]

**Comment by melissasamworth** [comment]
The play button only, right?

**Comment by melissasamworth** [comment]
![Image](https://github.com/StampyAI/AISafety.com/assets/825910/dec83b91-63b2-424a-b6af-db2582843c88)

This is like 20% bigger, thoughts @plexish @ricewithabee and if you could all tag soren in somehow too that would be great.

**Comment by ricewithabee** [comment]
Looks good to me.

**Comment by plexish** [comment]
> The play button only, right?

i was thinking the text next to it too, but don't have strong opinions, do what makes sense to you
