### ISSUE TITLE
/home: Fewer of the nodes should have ! marks

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#12]

**Comment by ricewithabee** [comment]
Update: no clear answer here on what should be done. Søren thinks it's fine how it is, as it authentically communicates our concern. Many people have given feedback saying it's too alarmist.

**Comment by melissasamworth** [comment]
@ricewithabee my final vote is to make like 1/4 or something of them exclamations

**Comment by melissasamworth** [comment]
<img width="1704" alt="image" src="https://github.com/StampyAI/AISafety.com/assets/825910/607ae038-4388-43bd-8e45-26867cd94440">

quick mockup

**Comment by melissasamworth** [comment]
I'll wait for Soren's signoff next week then upload
