### ISSUE TITLE
Upload latest version of website to GitHub

### ISSUE THREAD

**Issue by soerenelverlin** [StampyAI/AISafety.com#123]
In Webflow, you can save the entire website aisafety.com as code. This code is in GitHub, but is somewhat old. 

Your mission, should you choose to accept it, is to download the website to your local computer, download the existing code repository to your computer, overwrite the old code (from github) with the new code (that you downloaded from webflow). After this, you make it as a commit to github.

**Comment by triangle42** [comment]
Done with git commit [code base update (GitHub issue 123)](https://github.com/StampyAI/AISafety.com/commit/6546dd1c3859982157ec32d1266c3e7e7523f98a)

**Comment by triangle42** [comment]
Done with git commit [code base update (GitHub issue 123)](https://github.com/StampyAI/AISafety.com/commit/6546dd1c3859982157ec32d1266c3e7e7523f98a)
