### ISSUE TITLE
Refactor code to reduce duplication

### ISSUE THREAD

**Issue by soerenelverlin** [StampyAI/AISafety.com#125]
Many of our resource-pages include a code-box in webflow. I believe (70% confidence) that webflow includes a way to have shared code for all the pages. 

Be aware that code that looks identical, and is marked so in comments, might not actually be :)

The refactoring should not have any effects on behavior.

**Comment by triangle42** [comment]
I have added the shared code here:
![shared code](https://github.com/user-attachments/assets/1d8013b9-23f0-4055-ba0a-b488bd5f91cd)
