### ISSUE TITLE
Filter out OpenAI and career development roles from /jobs

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#131]
Note that this is a filtered list from 80k's database.

Hopefully this will be as simple as putting some filters in Airtable.

**Comment by bryceerobertson** [comment]
@triangle42 any chance you'd be interested in handling this? 🙏🏼

**Comment by triangle42** [comment]
> @triangle42 any chance you'd be interested in handling this? 🙏🏼

OK, I will do this.

**Comment by triangle42** [comment]
I have solved this.

**Comment by bryceerobertson** [comment]
Awesome! Nice work 🙏🏼
