### ISSUE TITLE
On mobile phone the cards often contain a lot of empty space at the bottom

### ISSUE THREAD

**Issue by triangle42** [StampyAI/AISafety.com#137]
For me, the empty space in the lower part of the cards was big in portrait mode on my Android smartphone and massive in landscape view mode.

**Comment by triangle42** [comment]
![Image](https://github.com/user-attachments/assets/2bb6c65e-adfc-4c6c-8f72-dd3e9645a2c8)
![Image](https://github.com/user-attachments/assets/9d49e7c6-a41f-4360-bd7b-471c2ccdaa42)
![Image](https://github.com/user-attachments/assets/66ee3a1e-a116-49b2-b301-c293e7b8168e)
![Image](https://github.com/user-attachments/assets/4ad949a0-eaf3-4d74-87d3-6b14fb748c4f)

**Comment by bryceerobertson** [comment]
Got it. I'll normalise the length of the descriptions for each listing and then after that we might want to change the sizes of the boxes
