### ISSUE TITLE
Meta tags need a banner (discussion)

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#14]

**Comment by plexish** [comment]
description done:

> A homepage for AI existential safety, tying together resources to help you learn about and mitigate the risks from advanced AI.

**Comment by melissasamworth** [comment]
Update: Melissa choose good image, upload

**Comment by melissasamworth** [comment]
Update: Melissa gets signoff on image

**Comment by melissasamworth** [comment]
Update: This is done, but it seems webflow wants us to repeat the open graph settings on each individual page. Worth doing?


![Image](https://github.com/StampyAI/AISafety.com/assets/825910/0f56a45e-18f9-4afd-a63d-dc7676c818d5)
