### ISSUE TITLE
/communities: Markdown not parsed in descriptions

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#19]
Communities page: There are a lot of cards which display additional links in brackets the text of their descriptions. (This is aesthetically displeasing, and also confusing.) Find all examples by Ctrl+F [http.

**Comment by melissasamworth** [comment]
I'm assigning this to nemo as it's over my head. We can probably discuss in a call together next week

**Comment by ricewithabee** [comment]
@melissasamworth we decided on the call on Saturday that I'll give it a go. But yep all good Philip can go ahead

**Comment by melissasamworth** [comment]
@ricewithabee Philip hasn't gotten back to me, so could you take this one after all?

**Comment by ricewithabee** [comment]
Yep

**Comment by ricewithabee** [comment]
I'm fixing this by removing all markdown from the source Airtables. We don't want links in the cards anyway since they won't be clickable.
