### ISSUE TITLE
/communities cards: Many have no redirect

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#23]

**Comment by melissasamworth** [comment]
@plexish what do you mean by this? All the cards links work for me

**Comment by plexish** [comment]
Not all, e.g. try Alignment Ecosystem Slack. The ones without a public facing invite link silently fail with the card display (table at least you could see that it was a missing field)

**Comment by plexish** [comment]
We could filter these out by default? e.g. Only show ones with links

**Comment by melissasamworth** [comment]
Update: invite link is a mailto to the contact
