### ISSUE TITLE
/projects: Many cards have invalid/missing redirect links

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#26]

**Comment by plexish** [comment]
/projects cards:
"Human Mind Simulation Project" navigates to https://www.aisafety.com/www.humanmind.uk, which displays a 404 page.
"Alignment Project Factory" has no description
"AI Safety Impact Markets" has no description

**Comment by ricewithabee** [comment]
- "Human Mind Simulation Project" is fixed
- "Alignment Project Factory" no longer exists in the Airtable and "AI Safety Impact Markets" has changed to "AI Safety Givewiki". Not sure how to get /projects to update this dynamically.

**Comment by melissasamworth** [comment]
Gah okay there are so many sync issues again. We might want to plan a call _just_ related to sync issues and invite Soren, Nemo, and maybe even Coby.

**Comment by ricewithabee** [comment]
I guess we can discuss on Saturday

**Comment by ricewithabee** [comment]
Discuss with Nemo next week (syncing issue).
