### ISSUE TITLE
/donation-guide: Guide focuses too much on very high amounts, and loads onto the highest amount right away

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#3]

**Comment by ricewithabee** [comment]
Loading onto highest amount has been fixed.

**Comment by melissasamworth** [comment]
@ricewithabee could be make it default to $1-5,000 instead of none of them? Also text should read $1 not $1,000

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/f501fa9b-e1f4-45bb-b4fb-8d05593c38b8)

**Comment by melissasamworth** [comment]
As far as redesigning this section, if you think it's worth re-writing @plexish or @ricewithabee feel free to do that. I don't think there is anything for me to do there right?

**Comment by ricewithabee** [comment]
> @ricewithabee could we make it default to $1-5,000 instead of none of them? Also text should read $1 not $1,000
> 
> ![Image](https://private-user-images.githubusercontent.com/825910/312257203-da81b6da-4fd9-40f5-9dec-7b25a586143d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTI5MjAsIm5iZiI6MTcxMDM1MjYyMCwicGF0aCI6Ii84MjU5MTAvMzEyMjU3MjAzLWRhODFiNmRhLTRmZDktNDBmNS05ZGVjLTdiMjVhNTg2MTQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNzU3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODU2NmIwMmI4MDA5OTQ4YzZlNmUzM2ZiYTZkZWY1ZDJjMTk3YzA5M2E5ZjM3ZWU1ODczYjI4MjNlNzQ2Nzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OhYNkjCHsq-jph0Jwirp-cEWJmajs_wLvOtTEY0TKoE)

Done

**Comment by ricewithabee** [comment]
> As far as redesigning this section, if you think it's worth re-writing @plexish or @ricewithabee feel free to do that. I don't think there is anything for me to do there right?

Yeah this is for plex
