### ISSUE TITLE
/communities: Add tag names on cards (discussion)

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#30]
Unclear what “Slack, Lively, Main focus is Al safety” means

**Comment by melissasamworth** [comment]
Update: the task is done. They're still awkwardly tall, mostly because some descriptions are still super long. Not launch blocking IMO but once descriptions are shorter I'll shorten the cards


![Image](https://github.com/StampyAI/AISafety.com/assets/825910/39c27d20-3f15-4026-89ef-1bcaf3bef56f)

**Comment by ricewithabee** [comment]
@melissasamworth can we do the same for /courses?

**Comment by ricewithabee** [comment]
@melissasamworth also for /jobs? Could potentially use icons instead of a tag names (e.g. 📍 instead of "Location")

**Comment by melissasamworth** [comment]
@ricewithabee yeah! could you create new tasks for these and assign to me?
