### ISSUE TITLE
/events: change to events & training and mimic .training

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#36]

**Comment by plexish** [comment]
/events isn't very useful yet, redirected to .training until further development

**Comment by plexish** [comment]
I think this should either duplicate .training's airtable views+add link+subscribe (once subscription is working again), or be split into /events and /training which duplicate a subset of .training.

**Comment by melissasamworth** [comment]
In general I really did want to design this one more. I think for now though let's discuss and come up with an MVP

**Comment by melissasamworth** [comment]
Update: Melissa designs, bryce implements

**Comment by ricewithabee** [comment]
Plex's suggestion: add all the .training views instead of the calendar. Should also be a button to add entry.

**Comment by ricewithabee** [comment]
@melissasamworth let me know when the design is done

**Comment by melissasamworth** [comment]
@ricewithabee I'm sorry, I have not done finished the designs for training vs. courses vs. events. Mainly because there is more information I need from everyone first, which I plan on getting at the meeting today

**Comment by melissasamworth** [comment]
@ricewithabee do you still want to do this one? I think it's

1. rename the page to "Events and training" and update this in the places it's referenced on home as well
2. Add the 3 airtables from .training
