### ISSUE TITLE
/communities: sorts alphabetically, should be custom

### ISSUE THREAD

**Issue by plexish** [StampyAI/AISafety.com#46]

**Comment by ricewithabee** [comment]
Where is this being sourced from? I don't think I have access @plexish

**Comment by melissasamworth** [comment]
Someone (honestly I forget who) and I figured out how to sort by the custom column instead, but we may have missed communities. I will try one more time to figure this out.

**Comment by plexish** [comment]
> Where is this being sourced from? I don't think I have access @plexish

the .com airtable, i'll get you credentials

**Comment by melissasamworth** [comment]
Update: Plex creates custom colum in Airtable

Melissa then references this column in Webflow

**Comment by melissasamworth** [comment]
No apologies necessary, thanks!
