### ISSUE TITLE
Update & proofread donation guide

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/AISafety.com#57]

**Comment by ricewithabee** [comment]
@plexish I can't find a website for Nonlinear Network Markets 

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/bdcef3d7-c8d3-46b4-9afc-9b441aabe3f0)

**Comment by ricewithabee** [comment]
@plexish I'm not sure what to link for "community" 

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/5f7b2087-6936-40a9-a802-d983f2e5458e)

**Comment by plexish** [comment]
> @plexish I can't find a website for Nonlinear Network Markets
> 
> ![Image](https://private-user-images.githubusercontent.com/98026499/309748128-bdcef3d7-c8d3-46b4-9afc-9b441aabe3f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjA2MjYsIm5iZiI6MTcxMDQyMDMyNiwicGF0aCI6Ii85ODAyNjQ5OS8zMDk3NDgxMjgtYmRjZWYzZDctYzhkMy00NmI0LTlhZmMtOWI0NDFhYWJlM2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyNDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2N2E5NTBjMjRkMTc4MDdkYTk5ZWU5NTQ1NDM2ZTA3ZTFkNzQwMWZhZGJmZGVkYzNiOWQ5ODZjYzRlMzg0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yG8G6x5h7Pu-ph5gbNx2VUpvswy8aSkdCL5c9HQhxow)

that's a typo, should be Nonlinear Network

**Comment by plexish** [comment]
> @plexish I'm not sure what to link for "community"
> 
> ![Image](https://private-user-images.githubusercontent.com/98026499/309749163-5f7b2087-6936-40a9-a802-d983f2e5458e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjA2MjYsIm5iZiI6MTcxMDQyMDMyNiwicGF0aCI6Ii85ODAyNjQ5OS8zMDk3NDkxNjMtNWY3YjIwODctNjkzNi00MGE5LWE4MDItZDk4M2YyZTU0NThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyNDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2VjZDViMTM1NzkzM2I4ZDdlMWM4NTA3NWI5MWI4NzI1NTQwZTAxZTAyODZjZTZjZDExOGE0MTI1MWJlOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jm8fuTIu_HCY8bFyPY_Z3CkmZ-f2UOb3XdIkJT_nrGQ)

.com/communities
