### ISSUE TITLE
/courses: checkboxes missing on mobile

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/AISafety.com#61]

**Comment by ricewithabee** [comment]
This appears to be intentional?

**Comment by melissasamworth** [comment]
Ah yeah this is not ideal. My design featured filters in a modal on mobile but it was too hard to implement. I still think we should implement this if we have the time.

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/88a9adca-3924-42cd-8ee2-5eab1f3a32ff)

@ricewithabee
