### ISSUE TITLE
/reading-guide on mobile: various bugs

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/AISafety.com#62]

**Comment by ricewithabee** [comment]
![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/6bf45460-5791-474d-b566-aad5179be54a)

**Comment by ricewithabee** [comment]
Text running away from box when spread over multiple lines:

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/c4b2f75e-204d-4ee5-924c-afb36d18b5be)

**Comment by ricewithabee** [comment]
Text out of line with bullets:


![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/197be436-6fa8-40ac-bb0e-e1285907819d)

**Comment by ricewithabee** [comment]
Tapping these links...

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/eb32a230-2eaa-4a69-98a3-1749a077bb72)

...leads to aisafety.info being opened inside the HTML embed:


![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/51675e7f-638a-4613-86b8-0c8eedcc1b68)

**Comment by plexish** [comment]
> Meh I really don't like the old stampy. I'd almost rather just link entirely to the new aisafety.info.
> 
> I think people will disagree with me here but @plexish @ricewithabee let me know your thoughts.
> 
> If not, let's consider which stampy dev we should assign these to.

I'm open to this, yeah. Feel free to switch over.

**Comment by ricewithabee** [comment]
Sounds good to me
