### ISSUE TITLE
/donation-guide on mobile: make tapping a button automatically scroll down to corresponding text

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#63]

**Comment by ricewithabee** [comment]
Interactions don't seem to be possible and entering custom code didn't work out for me, so I'm blocked. Best would be if someone who knows code were to check the custom code I added.

**Comment by melissasamworth** [comment]
Let's address this on a technical call

**Comment by ricewithabee** [comment]
Discuss with Nemo next week.

**Comment by melissasamworth** [comment]
update: nemo will address probably using custom code and a js call... make sure that this doesn't affect desktop

**Comment by bryceerobertson** [comment]
This seems much less necessary now that the number of Donation Amount buttons has been reduced to 4
