### ISSUE TITLE
New favicon

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#65]
I saw feedback that the exclamation point looked like it was a message from the browser, not our favicon

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/1ae7d1d9-4e5e-444c-98fa-451db2f9a1b5)

**Comment by melissasamworth** [comment]
Yes agreed.

I'm down with that, yeah. I was going to prioritize the various tasks and do them all at once just do to my working style right now, but if you want to use that one I'd be fine with it. Maybe the top right one or something could be an exclamation point

**Comment by bryceerobertson** [comment]
Done
