### ISSUE TITLE
Nav: word "workshops" is repeated under both Courses and Events

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/AISafety.com#68]
@melissasamworth do you want to change this? I'm not sure what the guidelines are.

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/584ae5c0-d2bb-4126-a492-a9d09bc4e626)

**Comment by melissasamworth** [comment]
Ideally yeah. @plexish would be better able to comment on which of these is best described as "workshop"

**Comment by ricewithabee** [comment]
I'll go ahead and fix these – it's always easy to change back again.

**Comment by plexish** [comment]
@ricewithabee only training should have workshops, not courses

**Comment by ricewithabee** [comment]
@melissasamworth what do you see? This is what I see

<img width="1728" alt="Screenshot 2024-04-04 at 12 41 01" src="https://github.com/StampyAI/AISafety.com/assets/98026499/a41c95d2-1ec1-49fb-aae2-b8bee39e1859">

**Comment by ricewithabee** [comment]
Ah I see the problem, I forgot to update the nav thing on the main page. Done now.
