### ISSUE TITLE
/many: Normalise card body text length

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#69]
- [x] /courses
- [x] /communities
- [x] /projects
- [x] /funders

At the moment they vary from one brief sentence like this...

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/eef8e47e-959d-4d7c-85c3-ea9c7a99b2ed)

...to excessively long paragraphs like this:

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/eabada60-c0b7-42f5-adf9-e6bf608d604f)

@melissasamworth I remember we discussed this on a meeting sometime but I can't see any issue for it. Should I do it?

**Comment by ricewithabee** [comment]
- [ ] /courses
- [ ] /communities
- [ ] /projects
- [ ] /funders

**Comment by ricewithabee** [comment]
The content of the text should also be checked and updated.

**Comment by melissasamworth** [comment]
Yes this would be amazing ✨.

As a side note, the eligible recipients should not be a paragraph of text, not sure why it shows up that way on just one card

**Comment by melissasamworth** [comment]
I think we'll want the text length of the projects cards normalized before Soeren's conference on Fri. Lmk if you want help with this. I imagine for mVP we could just use chatgpt to shorten
