### ISSUE TITLE
/funders: related resources have no links

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/AISafety.com#71]
@plexish or @melissasamworth do you know where these should link to?

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/846cd132-5ca4-42b8-aa9a-4b7e0624f015)

**Comment by melissasamworth** [comment]
@ricewithabee here's the second https://www.lesswrong.com/posts/WGpFFJo2uFe5ssgEb/an-overview-of-the-ai-safety-funding-situation but I have no idea for the first

**Comment by ricewithabee** [comment]
Thanks, second one is done ✅

@soerenelverlin do you know where the first one should lead?
