### ISSUE TITLE
/projects: change Airtable view

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/AISafety.com#73]
At the moment we're using the first one, but we're not sure how well maintained that is. The second one is the AED one, which we should use (I'm going to do a sweep of it this week to get it updated).

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/dd76ee3f-15d5-4f59-bcb9-6e60c0647973)

**Comment by ricewithabee** [comment]
@soerenelverlin I'm assuming you're the guy for this? I'd be happy to do it myself but I don't have access to Whalesync. If you'd prefer then feel free to send me the login and I'll do it

**Comment by ricewithabee** [comment]
I'll do this

**Comment by melissasamworth** [comment]
@ricewithabee just a note that a lot of these don't seem conducive to the design we're going for, like a lot have too long of paragraphs or are missing lots of info. Where else are you referencing this database?

<img width="577" alt="image" src="https://github.com/StampyAI/AISafety.com/assets/825910/63d8792f-4e2b-432a-8dcf-f00acc0ad9b7">

**Comment by ricewithabee** [comment]
@melissasamworth the Airtable view has been changed, but the cleaning of the data is still in progress – see #76
