### ISSUE TITLE
/many: clean up all data in Airtable

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#76]
- Check formatting/styling of all fields
- Check and update content of all fields
- Fill in all missing fields

- [x] /courses
- [x] /communities
- [x] /projects
    - [x] Send form to contacts for uncertain projects (in hidden Description Short field)
    - [x] plex: just contact for .info, otherwise me
- [x] /funders
- [x] /jobs

**Comment by melissasamworth** [comment]
@ricewithabee it might be nice to also have consistency e.g. dates are always the same format across all tables

**Comment by ricewithabee** [comment]
@melissasamworth I think the fields at the bottom of /projects cards should be something like:

Contact
[name]
[email address]

Status
[e.g. Launched]

And clicking on the card should launch a mailto: link for the email address above.

**Comment by melissasamworth** [comment]
<img width="425" alt="image" src="https://github.com/StampyAI/AISafety.com/assets/825910/9a8ae569-1303-43bd-878d-59651517a926">
Cool card designs will look like this and I'll link it out to the email. As far as the description sure, want to take care of that? Eventually I want to spend a minute thinking about how to describe it best but for now let's just do something quick.

As far as status, 8 statuses is too much for the brain to want to read and make sense of. Do you have any quick ideas for a simplified version here? Maybe even as simple as

Active
Paused
Project idea (or something to allude to the fact that no one has actually started on it)

<img width="353" alt="image" src="https://github.com/StampyAI/AISafety.com/assets/825910/023228ec-a3bb-4618-b06e-19ac0a61c1da">

**Comment by bryceerobertson** [comment]
Nice one.

Yeah you're totally right. I think I like this:
- Active
- Paused
- Seeking owner

**Comment by melissasamworth** [comment]
Yeah I like that

**Comment by melissasamworth** [comment]
FYI not sure this is the right task to comment this but only two projects are showing up on the live page rn

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/b368c45d-5a0d-4ef0-9455-4043ec562028)

**Comment by bryceerobertson** [comment]
Note to self: only showing Paused projects

**Comment by bryceerobertson** [comment]
@soerenelverlin is going to fix that buy since it's a filters problem

**Comment by bryceerobertson** [comment]
I'm still waiting on info from three project contacts about their project. Other than that it's finished.
