### ISSUE TITLE
/courses: if a course in Airtable has more than one "Category", only one is synced to the website

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#80]
This affects both the category displayed on that course's card as well as the Category filter.

Example:

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/c7683eac-0460-42a7-a109-7addee2d838c)

![Image](https://github.com/StampyAI/AISafety.com/assets/98026499/be08fb5c-4a89-4c85-a56c-af24ee9a7615)

**Comment by ricewithabee** [comment]
You're a magician
