### ISSUE TITLE
Implement analytics

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#84]
Sign up for the analytics tools, probably using the alignment proton dev email (ask Plex for this), and Soeren's payment information 🙏.

Figure out what steps are required to implement it and then implement it.

**Comment by bryceerobertson** [comment]
A couple people on the last AED call recommended https://matomo.org/ for non-cookies analytics. Want to check it out?

**Comment by melissasamworth** [comment]
Not sure why that is happening, @triangle42 any ideas? Otherwise perhaps contact support.

Re Bryce: hmm I see "session recordings", looks potentially promising

**Comment by bryceerobertson** [comment]
I've set up Matomo analytics: https://aisafety.matomo.cloud/

Now just waiting for some visitors 🤓

Anyone who wants the password send me a DM on Discord.
