### ISSUE TITLE
Try to find an alternative to Hotjar that doesn't use cookies

### ISSUE THREAD

**Issue by triangle42** [StampyAI/AISafety.com#89]

**Comment by triangle42** [comment]
I haven't found such an alternative. Maybe someone else is more successful.

**Comment by melissasamworth** [comment]
@triangle42 Bryce mentioned this one https://matomo.org/ 

It seems to have session recordings. Are you still interested in this task? If you want to keep going, it would be valuable to (1) ensure this does in fact have the session recordings we need, (2) try implementing it. No pressure though, you're a volunteer and you choose what you want to work on 🙏

I'll help out with 1.

**Comment by melissasamworth** [comment]
Followup: Session recordings seem good! 

@bryceerobertson @soerenelverlin if you want to weigh in
