### ISSUE TITLE
/projects misc (for new card design)

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#96]
/projects

1. Shorten descriptions
2. Update database so each project has a contact name (preferably first and last) and email  - If someone doesn't want to put their email (e.g. Plex I think?), I'd rather one of us just put our email, and when someone emails us we can send them to him (just put mine if no one else wants to)

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/961046da-00fb-482b-b43b-71a7baa72d67)

**Comment by melissasamworth** [comment]
@bryceerobertson I know someone of this is already being discussed in other issues or might be worth splitting out into a new task to assign to someone else. Feel free to re-organize it or ask me to (later), for now I'm just concentrating on doing the cards but want to make sure none of this is missed.

**Comment by bryceerobertson** [comment]
This is all in progress already

**Comment by melissasamworth** [comment]
Cool free free to delete this task
