### ISSUE TITLE
/funders: Fix recipient type (or remove from design)

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#97]
Recipient type column for Funders seems incomplete. E.g. SFF funds more than just non-profits right?

Either update this column or let's remove it from the design. I think it's find to remove it because it's not clear to me it adds much value. If we choose to do this assign it to me (Melissa).

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/9662e6f0-0520-45bf-be6f-446a1d6607d1)

**Comment by bryceerobertson** [comment]
I've updated it already as best I can, but for many funders it's hard to determine exactly who they do and don't fund. I agree it can be left out

**Comment by melissasamworth** [comment]
There's also "Eligible recipients" but this column also is not ideal. Should we just remove the recipients thing altogether? I think I'm in favor of that

**Comment by melissasamworth** [comment]
@plexish @soerenelverlin would like at least one of your final approval before doing this

**Comment by plexish** [comment]
I'm fine with it
