### ISSUE TITLE
/communities, /courses, /funders, /jobs: upload correct images

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/AISafety.com#99]
For the featured cards: 
- Manually upload all the images
- Manually add each image
- Note that I created a white square and added the images as backgrounds on that

![Image](https://github.com/StampyAI/AISafety.com/assets/825910/6a54b487-9aec-4b49-a677-e7c9fa56af76)

For the other cards:
- Hook the images up to Webflow by adding them to whalesync and whatever
- Hook the database item up with the images so all of the cards show the right images. This is probably going to be a bit confusing so let me know when you get to this step and I'll try to help.

**Comment by bryceerobertson** [comment]
@melissasamworth not sure whether it's better with or without the white background. What do you reckon?

**Comment by melissasamworth** [comment]
Oh wow that was a quick turnaround thanks 🙏.

Yeah I prefer without, actually looks really good! There are a few cases where dark logos have transparent bgs and we see nothing. Ultimately we should probably add a background and re-upload to the database (for the databases we control) but for now I think it's good
<img width="733" alt="image" src="https://github.com/StampyAI/AISafety.com/assets/825910/6d3a9e4e-b722-4a83-98f2-8f2744eefec2">

**Comment by bryceerobertson** [comment]
Most of them I can probably change the colour of the logos from black to white. I'll create an issue for me to do that.
